name: Python Artifact Demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Create-Artifact:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Python tool cache
        run: |
          echo "RUNNER_TOOL_CACHE=$RUNNER_TEMP/_toolcache" >> "$GITHUB_ENV"
          mkdir -p "$RUNNER_TEMP/_toolcache"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Show Python version
        run: python --version

      - name: Run Python program
        run: python app.py

      - name: Show generated file
        run: cat result.txt

      - name: Upload result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-result-file
          path: result.txt
