name: Python Artifact Demo

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Create-Artifact:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug runner environment
        run: |
          echo "===== ENVIRONMENT ====="
          echo "HOME=$HOME"
          echo "RUNNER_TOOL_CACHE=$RUNNER_TOOL_CACHE"
          echo "RUNNER_TEMP=$RUNNER_TEMP"
          echo "RUNNER_WORKSPACE=$RUNNER_WORKSPACE"
          echo "RUNNER_ROOT=$RUNNER_ROOT"

          echo "===== RUNNER VARIABLES ====="
          env | grep '^RUNNER_' | sort

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Show Python version
        run: python --version

      - name: Run Python program
        run: python app.py

      - name: Show generated file
        run: cat result.txt

      - name: Upload result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-result-file
          path: result.txt
